openapi: 3.0.3
info:
  title: Benny API
  version: 1.0.0
  description: Data extractor API for Benny app.
paths:
  /api/authenticate/:
    get:
      operationId: authenticate_retrieve
      tags:
      - authenticate
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/authenticate/{provider}/:
    post:
      operationId: authenticate_create
      description: |-
        Handle authentication based on the provided provider (e.g., Google).

        Args:
            request (HttpRequest): The HTTP request object.
            provider (str): The name of the authentication provider (e.g., 'google').

        Returns:
            Response: A DRF Response object containing user information on successful authentication,
                      or an error message on failure.

        Notes:
            - This view expects a POST request with a serialized token for the specified provider.
            - The authentication process uses the `AuthenticatorFactory` to create an appropriate
              authenticator for the given provider.
      parameters:
      - in: path
        name: provider
        schema:
          type: string
        required: true
      tags:
      - authenticate
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/extract_data/:
    post:
      operationId: extract_data_create
      description: |-
        Handle the extraction of data from the provided text.

        Args:
            request (HttpRequest): The Django request object.

        Returns:
            JsonResponse: A JSON response containing extracted data or an error message.

        Notes:
            - This view expects a POST request with a provided text.
            - The extraction process uses the Strategy Design Pattern and determines the appropriate
              extractor based on the content of the text.
      tags:
      - extract_data
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
