version: "3.8"

services:
  db:
    container_name: db
    image: postgres:14.3
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  web:
    container_name: web
    build:
      target: development_build
      context: .
    working_dir: /benny
    tty: true
    volumes:
      - .:/usr/src/benny
      - .psqlrc:/root/.psqlrc
      - .psql_history:/root/.psql_history
      - static-volume:/usr/src/benny/static
    env_file:
      - docker-compose.env
    # command: scripts/init_web.sh
    command: poetry run python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
  nginx:
    container_name: nginx
    command: nginx -g "daemon off;"
    depends_on:
      - web
    image: nginx:alpine
    restart: on-failure
    volumes:
      - ./nginx/web.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/local.crt:/etc/ssl/local.crt
      - ./nginx/local.key:/etc/ssl/local.key
      - static-volume:/usr/src/benny/static
      - .:/usr/src/benny
    ports:
      - "${NGINX_PORT:-443}:443"
      - "8888:80"
  redis:
    container_name: redis
    image: redis:6.2
    ports:
      - "6379"
  celery:
    container_name: celery
    build: .
    command: celery -A benny worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
  frontend:
    env_file:
      - frontend.env
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://web:8000

volumes:
  db-data:
  static-volume:
